### ISSUE TITLE
works the PCA9633?

### ISSUE THREAD

**Issue by Ataraxiall** [jveitchmichaelis/pca9632#2]
Good morning,

Is this module compatible with the PCA9633?

Thanks and best regards!

**Comment by jveitchmichaelis** [comment]
According to NXP [1], "The PCA9632 is a drop-in upgrade for the PCA9633 with 40× power reduction" - so I would say probably yes, but you should use the 9632 if available. I haven't tested it though!

[1] https://www.nxp.com/docs/en/data-sheet/PCA9632.pdf
